/** Authentication */
export const STORE_PHONE_AND_PASSWORD_WHEN_LOGIN = 'STORE_PHONE_AND_PASSWORD_WHEN_LOGIN'
export const STORE_USER_INFO_WHEN_REGISTER = 'STORE_USER_INFO_WHEN_REGISTER'
export const STORE_USER_INFO_WHEN_DONE_A_REGISTER_STEP = 'STORE_USER_INFO_WHEN_DONE_A_REGISTER_STEP'
export const CLEAR_USER_INFO_WHEN_DONE_REGISTER = 'CLEAR_USER_INFO_WHEN_DONE_REGISTER'

/**Message from server */
export const SET_MESSAGE_FROM_SERVER = 'SET_MESSAGE_FORM_SERVER'
export const CLEAR_MESSAGE_FROM_SERVER = 'CLEAR_MESSAGE_FROM_SERVER'