/** Authentication */
export const STORE_PHONE_AND_PASSWORD_WHEN_LOGIN = "STORE_PHONE_AND_PASSWORD_WHEN_LOGIN";
export const STORE_USER_INFO_WHEN_REGISTER = "STORE_USER_INFO_WHEN_REGISTER";
export const STORE_USER_INFO_WHEN_DONE_A_REGISTER_STEP =
    "STORE_USER_INFO_WHEN_DONE_A_REGISTER_STEP";
export const CLEAR_USER_INFO_WHEN_DONE_REGISTER = "CLEAR_USER_INFO_WHEN_DONE_REGISTER";
export const CLEAR_USER_INFO_LOGIN = "CLEAR_USER_INFO_LOGIN";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

/**Inbox */
export const STORE_INBOXS = "STORE_INBOXS";
export const GET_INBOXS_FROM_SERVER = "GET_INBOXS_FROM_SERVER";
export const STORE_CURRENT_INBOX = "STORE_CURRENT_INBOX";
export const RESET_NEW_MESSAGE = "RESET_NEW_MESSAGE";
export const STORE_OLDER_INBOXS = 'STORE_OLDER_INBOXS'

/**box chat */
export const GET_MESSAGE_IN_BOX_CHAT = "GET_MESSAGE_IN_BOX_CHAT";
export const STORE_MESSAGE_IN_BOX_CHAT = "GET_MESSAGE_IN_BOX_CHAT";
export const STORE_CURRENT_NUMBER_ID_INBOX = "STORE_CURRENT_NUMBER_ID_INBOX";
export const INITIALIZE_MESSAGE_IN_BOX_CHAT = "INITIALIZE_MESSAGE_IN_BOX_CHAT";
export const STORE_CURRENT_ROOM_ID = "STORE_CURRENT_ROOM_ID";
export const EXPRESS_REACTION = 'EXPRESS_REACTION'
/**friends and groups */
export const STORE_FRIENDS_LIST = "STORE_FRIENDS_LIST";
export const STORE_FRIENDS_REQUEST = "STORE_FRIENDS_REQUEST";
export const STORE_GROUPS_LIST = "STORE_GROUPS_LIST";
// export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
// export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";


/**socket */
export const UPDATE_MESSAGE_REALTIME = "UPDATE_MESSAGE_REALTIME";
export const STORE_REAL_TIME_MESSAGE = "STORE_REAL_TIME_MESSAGE";
export const STORE_REAL_TIME_RESPONSE = "STORE_REAL_TIME_RESPONSE";
export const UPDATE_LAST_MESSAGE_IN_INBOX = "UPDATE_LAST_MESSAGE_IN_INBOX";

/**Message from server */
export const SET_MESSAGE_FROM_SERVER = "SET_MESSAGE_FORM_SERVER";
export const CLEAR_MESSAGE_FROM_SERVER = "CLEAR_MESSAGE_FROM_SERVER";
