/** Authentication */
export const STORE_PHONE_AND_PASSWORD_WHEN_LOGIN = "STORE_PHONE_AND_PASSWORD_WHEN_LOGIN";
export const STORE_USER_INFO_WHEN_REGISTER = "STORE_USER_INFO_WHEN_REGISTER";
export const STORE_USER_INFO_WHEN_DONE_A_REGISTER_STEP =
    "STORE_USER_INFO_WHEN_DONE_A_REGISTER_STEP";
export const CLEAR_USER_INFO_WHEN_DONE_REGISTER = "CLEAR_USER_INFO_WHEN_DONE_REGISTER";
export const CLEAR_USER_INFO_LOGIN = "CLEAR_USER_INFO_LOGIN";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESSFUL= "LOGOUT_SUCCESSFUL";

/**Inbox */
export const STORE_INBOXS = "STORE_INBOXS";
export const GET_INBOXS_FROM_SERVER = "GET_INBOXS_FROM_SERVER";
export const STORE_CURRENT_INBOX = "STORE_CURRENT_INBOX";

/**box chat */
export const GET_MESSAGE_IN_BOX_CHAT = "GET_MESSAGE_IN_BOX_CHAT";
export const STORE_MESSAGE_IN_BOX_CHAT = "GET_MESSAGE_IN_BOX_CHAT";
export const GET_CURRENT_NUMBER_ID_BOX_CHAT = "GET_CURRENT_NUMBER_ID_BOX_CHAT";
export const INITIALIZE_MESSAGE_IN_BOX_CHAT = "INITIALIZE_MESSAGE_IN_BOX_CHAT";

/**Message from server */
export const SET_MESSAGE_FROM_SERVER = "SET_MESSAGE_FORM_SERVER";
export const CLEAR_MESSAGE_FROM_SERVER = "CLEAR_MESSAGE_FROM_SERVER";
